// gsap-animations-showcase/src/components/layout/Navbar.tsx
import { useEffect, useState } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { Menu, Moon, Sun, Sparkles, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useTheme } from '@/components/ThemeProvider'
import { cn } from '@/lib/utils'

const NAV_LINKS = [
  { to: '/', label: 'Home' },
  { to: '/animations', label: 'Animations' },
  { to: '/about', label: 'About' },
]

export function Navbar() {
  const { theme, toggle } = useTheme()
  const [open, setOpen] = useState(false)

  useEffect(() => {
    const handler = () => setOpen(false)
    window.addEventListener('resize', handler)
    return () => window.removeEventListener('resize', handler)
  }, [])

  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/60 bg-background/70 backdrop-blur-xl">
      <div className="container flex h-16 items-center justify-between">
        <Link
          to="/"
          className="flex items-center gap-2 font-semibold tracking-tight"
        >
          <Sparkles className="h-5 w-5 text-primary" />
          <span className="hidden sm:inline">GSAP Showcase</span>
          <span className="sm:hidden">GSAP</span>
        </Link>

        <nav className="hidden items-center gap-1 md:flex">
          {NAV_LINKS.map((link) => (
            <NavLink
              key={link.to}
              to={link.to}
              end={link.to === '/'}
              className={({ isActive }) =>
                cn(
                  'rounded-md px-3 py-2 text-sm font-medium transition-colors',
                  isActive
                    ? 'text-foreground bg-accent'
                    : 'text-muted-foreground hover:text-foreground hover:bg-accent/60',
                )
              }
            >
              {link.label}
            </NavLink>
          ))}
        </nav>

        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="icon"
            onClick={toggle}
            aria-label="Toggle theme"
          >
            {theme === 'dark' ? (
              <Sun className="h-4 w-4" />
            ) : (
              <Moon className="h-4 w-4" />
            )}
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="md:hidden"
            onClick={() => setOpen((o) => !o)}
            aria-label="Toggle menu"
            aria-expanded={open}
          >
            {open ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}
          </Button>
        </div>
      </div>

      {open && (
        <nav className="container flex flex-col gap-1 border-t border-border/60 py-3 md:hidden">
          {NAV_LINKS.map((link) => (
            <NavLink
              key={link.to}
              to={link.to}
              end={link.to === '/'}
              onClick={() => setOpen(false)}
              className={({ isActive }) =>
                cn(
                  'rounded-md px-3 py-2 text-sm font-medium transition-colors',
                  isActive
                    ? 'text-foreground bg-accent'
                    : 'text-muted-foreground hover:text-foreground hover:bg-accent/60',
                )
              }
            >
              {link.label}
            </NavLink>
          ))}
        </nav>
      )}
    </header>
  )
}

// ai-data-viz/src/components/Navbar.svelte
<script lang="ts">
  import { DATASETS } from '@/data/registry'
  import { href, router } from '@/lib/router.svelte'
  import { theme } from '@/lib/theme.svelte'

  let open = $state(false)

  const links = $derived([
    { label: 'Overview', path: '/' },
    ...DATASETS.map((d) => ({ label: d.name, path: `/d/${d.id}` })),
    { label: 'About', path: '/about' },
  ])
</script>

<header
  class="sticky top-0 z-40 border-b bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/65"
>
  <div class="container flex h-14 items-center gap-4">
    <a href={href('/')} class="flex shrink-0 items-center gap-2 font-semibold tracking-tight">
      <span
        class="grid h-6 w-6 place-items-center rounded-md text-[13px]"
        style:background="hsl(var(--primary) / 0.16)"
        style:color="var(--series-1)"
        aria-hidden="true">⌁</span
      >
      <span class="text-sm">AI Data Visualization</span>
    </a>

    <nav class="ml-auto hidden items-center gap-1 lg:flex" aria-label="Datasets">
      {#each links as link (link.path)}
        <a
          href={href(link.path)}
          class="rounded-md px-2.5 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
          class:bg-accent={router.isActive(link.path)}
          class:text-foreground={router.isActive(link.path)}
          aria-current={router.isActive(link.path) ? 'page' : undefined}
        >
          {link.label}
        </a>
      {/each}
    </nav>

    <button
      type="button"
      class="chip ml-auto lg:ml-0"
      onclick={() => theme.toggle()}
      aria-label="Switch to {theme.mode === 'dark' ? 'light' : 'dark'} mode"
    >
      {theme.mode === 'dark' ? '☾ Dark' : '☀ Light'}
    </button>

    <button
      type="button"
      class="chip lg:hidden"
      aria-expanded={open}
      aria-controls="mobile-nav"
      onclick={() => (open = !open)}
    >
      Menu
    </button>
  </div>

  {#if open}
    <nav id="mobile-nav" class="container grid grid-cols-2 gap-1 pb-3 lg:hidden" aria-label="Datasets">
      {#each links as link (link.path)}
        <a
          href={href(link.path)}
          class="rounded-md px-3 py-2 text-xs text-muted-foreground hover:bg-accent hover:text-foreground"
          class:bg-accent={router.isActive(link.path)}
          class:text-foreground={router.isActive(link.path)}
          onclick={() => (open = false)}
        >
          {link.label}
        </a>
      {/each}
    </nav>
  {/if}
</header>
